name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: rust_teams
        path: target/release/rust_teams.exe
