name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc
    
    - name: Build
      run: cargo build --release
    
    - name: Upload exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: rust_teams-exe
        path: target/release/rust_teams.exe
