name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install tools
        run: |
          rustup component add rustfmt clippy
          cargo install cargo-edit
      
      - name: Build
        run: |
          cargo build --release
          mkdir dist
          cp target/release/rust_teams.exe dist/
      
      - name: Package
        run: |
          $version = (Get-Content Cargo.toml | Select-String 'version = "(.+)"').Matches.Groups[1].Value
          Compress-Archive -Path dist/* -DestinationPath rust-teams-v${version}-win-x64.zip
      
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: rust-teams-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}